project:
  type: website
  output-dir: code

website:
  title: "AKDE minireview"
  navbar:
    left:
       - text: "Tutorial"
       - href: AKDE_R_tutorial.html
format:
  html:
    theme: simplex
    css: references/styles.css
    toc: true

editor: visual

