<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Inês Silva">
<meta name="author" content="Christen H. Fleming">
<meta name="author" content="Michael J. Noonan">
<meta name="author" content="Jesse Alston">
<meta name="author" content="Cody Folta">
<meta name="author" content="William F. Fagan">
<meta name="author" content="Justin M. Calabrese">
<meta name="dcterms.date" content="2023-03-31">
<meta name="description" content="A step-by-step R tutorial using the ‘ctmm’ package">

<title>AKDE minireview - Guide to autocorrelated home range estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">AKDE minireview</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="dropdown-header">
 <span class="menu-text">AKDE_R_tutorial.qmd</span></li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a>
  <ul class="collapse">
  <li><a href="#step-1.-formatting-and-loading-an-animal-tracking-dataset" id="toc-step-1.-formatting-and-loading-an-animal-tracking-dataset" class="nav-link" data-scroll-target="#step-1.-formatting-and-loading-an-animal-tracking-dataset"><strong>Step 1.</strong> – Formatting and loading an animal tracking dataset</a>
  <ul class="collapse">
  <li><a href="#buffalo-tracking-data" id="toc-buffalo-tracking-data" class="nav-link" data-scroll-target="#buffalo-tracking-data">1.1. Buffalo tracking data</a></li>
  <li><a href="#gazelle-tracking-data" id="toc-gazelle-tracking-data" class="nav-link" data-scroll-target="#gazelle-tracking-data">1.2. Gazelle tracking data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a>
  <ul class="collapse">
  <li><a href="#step-2.-checking-for-the-range-residency-assumption" id="toc-step-2.-checking-for-the-range-residency-assumption" class="nav-link" data-scroll-target="#step-2.-checking-for-the-range-residency-assumption"><strong>Step 2.</strong> – Checking for the <em>range residency</em> assumption</a></li>
  <li><a href="#step-3.-selecting-the-best-fit-movement-model-through-model-selection" id="toc-step-3.-selecting-the-best-fit-movement-model-through-model-selection" class="nav-link" data-scroll-target="#step-3.-selecting-the-best-fit-movement-model-through-model-selection"><strong>Step 3.</strong> – Selecting the best-fit movement model through <em>model selection</em></a></li>
  <li><a href="#step-4.-feeding-a-movement-model-into-the-home-range-estimator" id="toc-step-4.-feeding-a-movement-model-into-the-home-range-estimator" class="nav-link" data-scroll-target="#step-4.-feeding-a-movement-model-into-the-home-range-estimator"><strong>Step 4.</strong> – Feeding a movement model into the <em>home range estimator</em></a></li>
  <li><a href="#step-5.-evaluating-additional-biases-applying-mitigation-measures" id="toc-step-5.-evaluating-additional-biases-applying-mitigation-measures" class="nav-link" data-scroll-target="#step-5.-evaluating-additional-biases-applying-mitigation-measures"><strong>Step 5.</strong> – Evaluating additional <em>biases</em>, applying <em>mitigation measures</em></a>
  <ul class="collapse">
  <li><a href="#buffalo-tracking-data-1" id="toc-buffalo-tracking-data-1" class="nav-link" data-scroll-target="#buffalo-tracking-data-1">5.1. Buffalo tracking data</a></li>
  <li><a href="#gazelle-tracking-data-1" id="toc-gazelle-tracking-data-1" class="nav-link" data-scroll-target="#gazelle-tracking-data-1">5.2. Gazelle tracking data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary">Glossary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Guide to autocorrelated home range estimation</h1>
</div>

<div>
  <div class="description">
    <p><strong>A step-by-step R tutorial using the ‘ctmm’ package</strong></p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Inês Silva </p>
             <p>Christen H. Fleming </p>
             <p>Michael J. Noonan </p>
             <p>Jesse Alston </p>
             <p>Cody Folta </p>
             <p>William F. Fagan </p>
             <p>Justin M. Calabrese </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>This tutorial is a companion piece to our manuscript <strong><em>“Autocorrelation-informed home range estimation: a review and practical guide”</em></strong>. Manuscript was published in <a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13786">Methods in Ecology and Evolution</a>. Preprint is also available on <a href="https://ecoevorxiv.org/repository/view/4026/">EcoEvoRxiv</a>. For any definitions, check the main manuscript or the <em><a href="#glossary">Glossary</a></em>.</p>
<p><em>To cite this material:</em></p>
<blockquote class="blockquote">
<p>Silva, I., Fleming, C. H., Noonan, M. J., Alston, J., Folta, C., Fagan, W. F., &amp; Calabrese, J. M. (2022). Autocorrelation‐informed home range estimation: A review and practical guide. Methods in Ecology and Evolution, 13(3), 534-544.</p>
</blockquote>
<p>https://ecoisilva.github.io/AKDE_minireview/code/AKDE_R-tutorial.html</p>
<section id="introduction" class="level1 page-columns page-full">
<h1>Introduction</h1>
<p><strong><em>Home range</em></strong> estimation is a key output from animal tracking datasets, but the inherent properties of animal movement can lead traditional methods to under- or overestimated their size. <strong>Autocorrelated Kernel Density Estimation (AKDE)</strong> methods were designed to be statistically efficient while explicitly dealing with the complexities and biases of modern movement data, such as <em>autocorrelation</em>, <em>small sample sizes</em>, and <em>missing or irregularly sampled data</em>.</p>
<aside>
<em>Home range</em>: the area repeatedly used throughout an animal’s lifetime for all its normal behaviors and activities, excluding occasional exploratory moves.
</aside>
<p>The <strong>AKDE</strong> family of home range estimators will be run using <strong>R software</strong> (<a href="https://www.r-project.org/" class="uri">https://www.r-project.org/</a>) and the <code>ctmm</code> package <span class="citation" data-cites="calabrese_ctmm_2016">(<a href="#ref-calabrese_ctmm_2016" role="doc-biblioref">Calabrese et al., 2016</a>)</span>. The techniques and mitigation measures available within this package include:</p>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> Method </th>
   <th style="text-align:left;font-weight: bold;"> When to run? </th>
   <th style="text-align:left;font-weight: bold;"> What does it do? </th>
   <th style="text-align:left;font-weight: bold;"> R function </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> AKDE </td>
   <td style="text-align:left;"> Tracking data is autocorrelated </td>
   <td style="text-align:left;"> Estimates range distributions from autocorrelated data, by conditioning on an autocorrelation model. </td>
   <td style="text-align:left;font-family: monospace;"> akde(…, debias = FALSE) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AKDEc </td>
   <td style="text-align:left;"> If using GRF-based KDEs (such as AKDE) </td>
   <td style="text-align:left;"> Removes the tendency of Gaussian reference function (GRF) methods  to overestimate the area of home ranges. </td>
   <td style="text-align:left;font-family: monospace;"> akde(…, debias = TRUE) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> pHREML </td>
   <td style="text-align:left;"> Small (absolute and effective) sample sizes </td>
   <td style="text-align:left;"> Improves upon ML and REML autocorrelation estimation, mitigating small sample size biases. </td>
   <td style="text-align:left;font-family: monospace;"> ctmm.select(…, method = "pHREML") </td>
  </tr>
  <tr>
   <td style="text-align:left;"> wAKDEc </td>
   <td style="text-align:left;"> Irregular sampling schedules or missing data </td>
   <td style="text-align:left;"> Upweights observations that occur during under-sampled times, while downweighting those occurring during over-sampled times. </td>
   <td style="text-align:left;font-family: monospace;"> akde(…, weights = TRUE) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Parametric bootstrap </td>
   <td style="text-align:left;"> Extremely small effective sample size </td>
   <td style="text-align:left;"> Calculates and corrects for autocorrelation estimation biases, by simulating from an approximate sampling distribution. </td>
   <td style="text-align:left;font-family: monospace;"> ctmm.boot(...) </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>AKDE<sub>c</sub> and pHREML are default arguments within the <code>akde()</code> and <code>ctmm.select()</code> functions, respectively. Both measures will run automatically if arguments <code>debias</code> and <code>method</code> are left unspecified. For most situations, we recommend keeping both of these arguments as the default.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Installing &amp; loading package:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ctmm"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ctmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="data-preparation" class="level1 page-columns page-full">
<h1>Data Preparation</h1>
<p>We will use two datasets, both available within the <code>ctmm</code> package: African buffalos (<em>Syncerus caffer</em>), and Mongolian gazelles (<em>Procapra gutturosa</em>). Information on the data collection protocol is available in Cross <em>et al.</em> <span class="citation" data-cites="cross_disease_2009">(<a href="#ref-cross_disease_2009" role="doc-biblioref">2009</a>)</span> and Fleming <em>et al.</em> <span class="citation" data-cites="fleming_fine-scale_2014">(<a href="#ref-fleming_fine-scale_2014" role="doc-biblioref">2014</a>)</span>. The <code>ctmm</code> package requires data to conform to Movebank naming conventions (<a href="https://www.movebank.org/node/2381" class="uri">https://www.movebank.org/node/2381</a>). We recommend uploading your data to Movebank (<a href="http://www.movebank.org/" class="uri">http://www.movebank.org/</a>) as this will facilitate data preparation, and ensure that your data are correctly formatted for <code>ctmm</code>. If needed, Movebank allows you to keep your data private.</p>
<p>We will focus on the simplest data structure:</p>
<ul>
<li><code>animal ID</code> or <code>ID</code> — An individual identifier for each animal tracked;</li>
<li><code>timestamp</code> or <code>t</code> — The date and time corresponding to a sensor measurement;
<ul>
<li><strong>Example</strong>: 2021-01-01 18:31:00.000
<ul>
<li><strong>Format</strong>: yyyy-MM-dd HH:mm:ss.SSS</li>
</ul></li>
</ul></li>
<li><code>longitude</code> or <code>x</code> — The geographic longitude of the location as estimated by the sensor;
<ul>
<li><strong>Example</strong>: -121.1761111
<ul>
<li><strong>Units</strong>: decimal degrees, WGS84 reference system.</li>
</ul></li>
</ul></li>
<li><code>latitude</code> or <code>y</code> — The geographic latitude of the location as estimated by the sensor;
<ul>
<li><strong>Example</strong>: -41.0982423
<ul>
<li><strong>Units</strong>: decimal degrees, WGS84 reference system.</li>
</ul></li>
</ul></li>
</ul>
<p>Location can also be described as UTM locations instead of latitude/longitude. In this case, you should provide <code>UTM easting</code>, <code>UTM northing</code>, and <code>UTM zone</code>. For all terms and conventions, please see the full vocabulary list here: <a href="http://vocab.nerc.ac.uk/collection/MVB/current/" class="uri">http://vocab.nerc.ac.uk/collection/MVB/current/</a>.</p>
<section id="step-1.-formatting-and-loading-an-animal-tracking-dataset" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="step-1.-formatting-and-loading-an-animal-tracking-dataset"><strong>Step 1.</strong> – Formatting and loading an animal tracking dataset</h2>
<p>You can import data into R through the <code>read.table()</code> or <code>read.csv()</code> functions; make sure to navigate to the appropriate folder or working directory. You can find two example files within the GitHub repository <a href="https://github.com/ecoisilva/AKDE_minireview/tree/main/data">data folder</a>. To read these .csv files into R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"here"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">here</span>() <span class="co"># your working directory</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># First, list all files in a specific folder:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="st">"data"</span>) <span class="co"># verify that your file appears here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then load the file:</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>animal0_longlat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data/example_data_longlat.csv"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(animal0_longlat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID        timestamp longitude latitude
1 animal0 2005-07-14 05:35  30.59648 65.24774
2 animal0 2005-07-14 07:35  30.53256 65.27085
3 animal0 2005-07-14 08:34  30.52398 65.26446
4 animal0 2005-07-14 09:35  30.52848 65.25948
5 animal0 2005-07-14 10:35  30.53382 65.26643
6 animal0 2005-07-14 11:34  30.49970 65.27868</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>animal0_utm <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data/example_data_utm.csv"</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(animal0_utm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID        timestamp UTM.Easting UTM.Northing  UTM.zone
1 animal0 14/07/2005 05:35    387730.0      7238204 36 +north
2 animal0 14/07/2005 07:35    384846.3      7240894 36 +north
3 animal0 14/07/2005 08:34    384418.1      7240197 36 +north
4 animal0 14/07/2005 09:35    384606.5      7239634 36 +north
5 animal0 14/07/2005 10:35    384885.8      7240399 36 +north
6 animal0 14/07/2005 11:34    383347.9      7241826 36 +north</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finally, convert to telemetry object:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>animal0a <span class="ot">&lt;-</span> <span class="fu">as.telemetry</span>(animal0_longlat)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>animal0b <span class="ot">&lt;-</span> <span class="fu">as.telemetry</span>(animal0_utm)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># if left unspecified, as.telemetry() will assume timezone = UTC, datum = WGS84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Both these files represent the same individual, with either <em>longitude</em>/<em>latitude</em>, or UTM coordinates (<em>easting</em>, <em>northing</em>, and <em>zone</em>), and both outputs —<code>animal0a</code> and <code>animal0b</code>— will show the same coordinates after conversion. In general, the <code>as.telemetry()</code> function will immediately identify the columns if they are correctly named, convert the projection if needed, and then output the minimum sampling interval for each individual in the dataset. In this example, <code>animal0</code> has a minimum sampling interval of 59 minutes.</p>
<section id="buffalo-tracking-data" class="level3">
<h3 class="anchored" data-anchor-id="buffalo-tracking-data">1.1. Buffalo tracking data</h3>
<p>For this tutorial, we will use data already prepared into a list of <code>telemetry</code> objects. We can load it directly from the <code>ctmm</code> R package with the <code>data()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"buffalo"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>animal1_buffalo <span class="ot">&lt;-</span> buffalo[[<span class="dv">4</span>]] <span class="co"># selecting individual number 4</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(animal1_buffalo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                timestamp longitude  latitude          t         x         y
17517 2006-04-25 05:09:00  31.73749 -24.19705 1145941740 -51803.35 -2715.663
17518 2006-04-25 06:09:00  31.73653 -24.19929 1145945340 -51569.29 -2845.660
17519 2006-04-25 07:09:00  31.73946 -24.20100 1145948940 -51340.72 -2576.353
17520 2006-04-25 08:09:00  31.73987 -24.20092 1145952540 -51344.11 -2533.788
17521 2006-04-25 10:09:00  31.74086 -24.20365 1145959740 -51029.45 -2474.771
17522 2006-04-25 11:09:00  31.74098 -24.20370 1145963340 -51022.23 -2463.655</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting locations:</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal1_buffalo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AKDE_R-tutorial_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid"></p>
</div>
</div>
<p>This dataset showcases an irregular sampling schedule: the buffalo nicknamed <em>“Pepper”</em> had a sampling rate shift from one fix every hour to one fix every two hours. We will use this dataset to highlight data irregularity and the <strong>wAKDE</strong> mitigation measure.</p>
</section>
<section id="gazelle-tracking-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="gazelle-tracking-data">1.2. Gazelle tracking data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"gazelle"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>animal2_gazelle <span class="ot">&lt;-</span> gazelle[[<span class="dv">11</span>]] <span class="co"># selecting individual number 11</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(animal2_gazelle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             x          y       t
2742  18152.70  -8539.799       0
2743  15931.16 -32069.788 1306800
2744  17678.84 -28632.329 1396800
2745  23135.50 -23820.789 1486800
2746 -20310.78  20348.792 2419200
2747 -17920.31  20598.668 2509200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting locations:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal2_gazelle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AKDE_R-tutorial_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid"></p>
</div>
</div>
<aside>
<em>Home range crossing time</em>: the time required for an animal to cross the linear extent of its home range.
</aside>
<p>Mongolian gazelles have a <strong><em>home range crossing time</em></strong> of a few months, and with a maximum longevity around 10 years, it is impossible to get a considerable <strong><em>effective sample size</em></strong> no matter the study duration <span class="citation" data-cites="fleming_overcoming_2019">(<a href="#ref-fleming_overcoming_2019" role="doc-biblioref">Fleming et al., 2019</a>)</span>. We will use this dataset to highlight how to check <strong><em>effective sample size</em></strong> and apply the <strong>parametric bootstrap</strong> mitigation.</p>
<aside>
<em>Effective sample size (N)</em>: number of range crossings that occurred during the observation period. Can be roughly estimated by dividing the duration of the tracking dataset by the average home range crossing time parameter.
</aside>
<hr>
</section>
</section>
</section>
<section id="data-analysis" class="level1 page-columns page-full">
<h1>Data Analysis</h1>
<section id="step-2.-checking-for-the-range-residency-assumption" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="step-2.-checking-for-the-range-residency-assumption"><strong>Step 2.</strong> – Checking for the <em>range residency</em> assumption</h2>
<p>First, we want to check if our first tracking dataset (<code>animal1_buffalo</code>) can be used for home range estimation by checking for <strong><em>range residency</em></strong>. To achieve this, we calculate the <strong>semi-variance function (SVF)</strong>, and visualize it through the <code>variogram()</code> function.</p>
<aside>
<em>Range residency</em>: the tendency of an animal to remain within their home range.
</aside>
<p><strong>Variograms</strong> are an unbiased way to visualize <em>autocorrelation</em> structure, representing the average square displacement (y-axis) over a specific time lag (x-axis). To facilitate interpretation, we have the <strong>SVF</strong> of <code>animal1_buffalo</code> zoomed out (right) to showcase all time lags and (left) zoomed in to showcase time lags up to two months:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>level <span class="ot">&lt;-</span> <span class="fl">0.95</span> <span class="co"># we want to display 95% confidence intervals</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>xlim <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span> <span class="sc">%#%</span> <span class="st">"month"</span>) <span class="co"># to create a window of 2 months</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>SVF <span class="ot">&lt;-</span> <span class="fu">variogram</span>(animal1_buffalo)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SVF, <span class="at">fraction =</span> <span class="dv">1</span>, <span class="at">level =</span> level)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># adding a line at 1 month </span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SVF, <span class="at">xlim =</span> xlim, <span class="at">level =</span> level)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AKDE_R-tutorial_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can see that the variogram flattens (<em>i.e.</em>, reaches an asymptote) after approximately <strong>1 month</strong> (<span style="color: red;">red</span> line). This also indicates at how coarse the timeseries needs to be to assume independence (no autocorrelation), and corresponds to when traditional methods —such as <strong>minimum convex polygons (MCPs)</strong> and <strong>Kernel Density Estimators (KDEs)</strong>— could be applied without violating their assumptions.</p>
</section>
<section id="step-3.-selecting-the-best-fit-movement-model-through-model-selection" class="level2">
<h2 class="anchored" data-anchor-id="step-3.-selecting-the-best-fit-movement-model-through-model-selection"><strong>Step 3.</strong> – Selecting the best-fit movement model through <em>model selection</em></h2>
<p>It is necessary to choose a home range estimator that accounts for the autocorrelated structure of the data, now that we see that it is <strong>not</strong> independently and identically distributed (non-IID). We need to test what movement model may explain the autocorrelated structure of our tracking data. We can run different movement processes with <strong>maximum likelihood (ML)</strong> or other parameter estimators, such as <strong>perturbative Hybrid REML (pHREML)</strong>. To facilitate further comparisons, we will run both ML and pHREML with the <code>ctmm.select</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate an automated model guesstimate:</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>GUESS1 <span class="ot">&lt;-</span> <span class="fu">ctmm.guess</span>(animal1_buffalo, <span class="at">interactive =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Automated model selection, starting from GUESS:</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>FIT1_ML <span class="ot">&lt;-</span> <span class="fu">ctmm.select</span>(animal1_buffalo, GUESS1, <span class="at">method =</span> <span class="st">'ML'</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>FIT1_pHREML <span class="ot">&lt;-</span> <span class="fu">ctmm.select</span>(animal1_buffalo, GUESS1, <span class="at">method =</span> <span class="st">'pHREML'</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="do">## reminder: it will default to pHREML if no method is specified.</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FIT1_ML)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FIT1_pHREML)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Within these summaries, <code>$name</code> provides the selected best-fit model, <code>$DOF</code> provides information on the degrees of freedom (where <code>$DOF["area"]</code> corresponds to the <strong><em>effective sample size</em></strong> of the home-range area estimate), and <code>$CI</code> are the parameter outputs (area, position autocorrelation timescale, velocity autocorrelation timescale, and speed).</p>
<p>The typical pool of candidate models includes isotropic (when diffusion is the same in every direction; symmetrical) and anisotropic (when diffusion varies with direction; asymmetrical) variants. The automated model selection shows that <em>OUF anisotropic</em> (anisotropic Ornstein-Uhlenbeck foraging process) is our best-fit model. This movement process features a home range, correlated positions, and correlated velocities. To check the full model selection table, we can run the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>FIT1_pHREML_verbose <span class="ot">&lt;-</span> <span class="fu">ctmm.select</span>(animal1_buffalo, GUESS1, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FIT1_pHREML_verbose)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By adding the argument <code>verbose = TRUE</code> we have access to the model selection table. By default, model selection is based on <em>Akaike’s Information Criterion adjusted for small sample sizes</em> (AICc). The <code>ctmm</code> package also offers BIC, LOOCV, and HSCV. LOOCV seems to work slightly better for very small datasets, but we recommend AICc for the majority of datasets.</p>
</section>
<section id="step-4.-feeding-a-movement-model-into-the-home-range-estimator" class="level2">
<h2 class="anchored" data-anchor-id="step-4.-feeding-a-movement-model-into-the-home-range-estimator"><strong>Step 4.</strong> – Feeding a movement model into the <em>home range estimator</em></h2>
<p>Now we can fit this movement process into the <code>akde()</code> function, and estimate the home range of <code>animal1_buffalo</code>. This function currently defaults to the <strong>area-corrected AKDE</strong>, or <strong>AKDEc</strong> (Fleming &amp; Calabrese 2017):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run an area-corrected AKDE:</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>UD1_ML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal1_buffalo, FIT1_ML)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>UD1_pHREML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal1_buffalo, FIT1_pHREML)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(UD1_pHREML)<span class="sc">$</span>CI <span class="co"># home range area estimation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have calculated our home range for <code>animal1_buffalo</code>, resulting in an estimation of 757 km<sup>2</sup> (with 95% confidence intervals: 430–1,175 km<sup>2</sup>).</p>
</section>
<section id="step-5.-evaluating-additional-biases-applying-mitigation-measures" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="step-5.-evaluating-additional-biases-applying-mitigation-measures"><strong>Step 5.</strong> – Evaluating additional <em>biases</em>, applying <em>mitigation measures</em></h2>
<section id="buffalo-tracking-data-1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="buffalo-tracking-data-1">5.1. Buffalo tracking data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(UD1_pHREML)<span class="sc">$</span>DOF[<span class="st">"area"</span>] <span class="co"># effective sample size of animal1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    area 
15.65773 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(animal1_buffalo) <span class="co"># absolute sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1725</code></pre>
</div>
</div>
<p>Our output here also reveals more information regarding our dataset: the <strong><em>effective sample size (N)</em></strong> and the <strong><em>absolute sample size (</em>n<em>)</em></strong>. We can return this measure with the <code>summary</code> function: in our case, the <em>N</em> for <code>animal1_buffalo</code> is 15.7. Comparatively, our <strong><em>absolute sample size</em></strong> is easy to output, as it is the total number of observations within our dataset (<em>n</em> = 1,725).</p>
<aside>
<em>Absolute sample size (n)</em>: the number of observations (fixes) in a dataset.
</aside>
<p>As mentioned earlier, <code>animal1_buffalo</code> had a device malfunction that led GPS fixes to shift from one fix per hour, to one fix every two hours. As such, this individual is particularly suited for a <strong>weighted AKDEc</strong> (or <strong>wAKDEc</strong>), so we can re-run the function with weights set to <code>TRUE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>UD1w_pHREML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal1_buffalo, FIT1_pHREML, <span class="at">weights =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(UD1w_pHREML)<span class="sc">$</span>CI <span class="co"># home range area estimation (weighted)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our new home range area estimation for <code>animal1_buffalo</code> is 761 km<sup>2</sup> (with 95% confidence intervals: 432–1,182 km<sup>2</sup>). We can now plot our home range estimate for <code>animal1_buffalo</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating an extent that includes both UDs at the 95% CI level:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>EXT <span class="ot">&lt;-</span> <span class="fu">extent</span>(<span class="fu">list</span>(UD1_ML, UD1_pHREML, UD1w_pHREML), <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting pHREML (with and without weights) side-by-side:</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal1_buffalo, <span class="at">UD =</span> UD1_pHREML, <span class="at">ext =</span> EXT)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="fu">expression</span>(<span class="st">"pHREML AKDE"</span>[<span class="st">"C"</span>]))</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal1_buffalo, <span class="at">UD =</span> UD1w_pHREML, <span class="at">ext =</span> EXT)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="fu">expression</span>(<span class="st">"pHREML wAKDE"</span>[<span class="st">"C"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AKDE_R-tutorial_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid"></p>
</div>
</div>
<p>For <code>animal1_buffalo</code>, the difference between model parameter estimators is not substantial; we only have a ~5.7% AKDE area underestimation by ML compared to pHREML. However, the data fits the spatial locations much better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>( <span class="dv">1</span> <span class="sc">-</span> <span class="fu">summary</span>(UD1_ML)<span class="sc">$</span>CI[<span class="dv">1</span>,<span class="dv">2</span>] <span class="sc">/</span> <span class="fu">summary</span>(UD1w_pHREML)<span class="sc">$</span>CI[<span class="dv">1</span>,<span class="dv">2</span>] ) <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.737587</code></pre>
</div>
</div>
</section>
<section id="gazelle-tracking-data-1" class="level3">
<h3 class="anchored" data-anchor-id="gazelle-tracking-data-1">5.2. Gazelle tracking data</h3>
<p>We can also check the difference with <code>animal2_gazelle</code>’s tracking data, where the small <strong><em>effective sample size</em></strong> issue is clearer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>GUESS2 <span class="ot">&lt;-</span> <span class="fu">ctmm.guess</span>(animal2_gazelle, <span class="at">interactive =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>FIT2_ML <span class="ot">&lt;-</span> <span class="fu">ctmm.select</span>(animal2_gazelle, GUESS2, <span class="at">method =</span> <span class="st">'ML'</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>FIT2_pHREML <span class="ot">&lt;-</span> <span class="fu">ctmm.select</span>(animal2_gazelle, GUESS2, <span class="at">method =</span> <span class="st">'pHREML'</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>UD2_ML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal2_gazelle, FIT2_ML)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>UD2_pHREML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal2_gazelle, FIT2_pHREML)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With <code>animal2_gazelle</code>, we have a more substantial area underestimation by ML compared to pHREML (~15.2%). We can also see that our <strong><em>effective sample size</em></strong> is only 4.5, with an <strong><em>absolute sample size</em></strong> of 49 (<em>N</em> <span class="math inline">\ll</span> <em>n</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>( <span class="dv">1</span> <span class="sc">-</span> <span class="fu">summary</span>(UD2_ML)<span class="sc">$</span>CI[<span class="dv">1</span>,<span class="dv">2</span>] <span class="sc">/</span> <span class="fu">summary</span>(UD2_pHREML)<span class="sc">$</span>CI[<span class="dv">1</span>,<span class="dv">2</span>] ) <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.16696</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(UD2_pHREML)<span class="sc">$</span>DOF[<span class="st">"area"</span>] <span class="co"># effective sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    area 
4.528926 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(animal2_gazelle) <span class="co"># absolute sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49</code></pre>
</div>
</div>
<p>At this point, we have selected a movement process, fed it into a home range area estimation with different model parameter estimators, and corrected for irregular sampling rates. With small <strong><em>effective sample sizes</em></strong>, it is important to see if <strong>parametric bootstrapping</strong> may be worth it to further reduce our estimation error. In order to do so, we can check the expected order of bias from pHREML:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected order of pHREML bias:</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="fu">summary</span>(FIT2_pHREML)<span class="sc">$</span>DOF[<span class="st">'area'</span>]<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      area 
0.04875393 </code></pre>
</div>
</div>
<p>The bias is currently <span class="math inline">\mathcal{O}(5\%)</span> (“in the order of” 5%). As such, we will run parametric bootstrapping for <code>animal2_gazelle</code>. The relative error target is 1% by default (<code>argument error = 0.01</code>), but can be adjusted if necessary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>start_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>() <span class="co"># start recording running time</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>BOOT <span class="ot">&lt;-</span> <span class="fu">ctmm.boot</span>(animal2_gazelle, FIT2_pHREML, <span class="at">trace =</span> <span class="dv">2</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="do">## note: this function incurs substantial computational cost, may take hours.</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>( total_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>() <span class="sc">-</span> start_time ) <span class="co"># output running time</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(BOOT)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="fu">summary</span>(BOOT)<span class="sc">$</span>DOF[<span class="st">'area'</span>]<span class="sc">^</span><span class="dv">3</span> <span class="co"># expected order of bias</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that the expected order of bias was reduced to 2.3%, which is comparable to the numerical error target of 1%. To reduce the numerical error further, we would need to change the default relative error target of <code>ctmm.boot</code>, but the computational cost would continue to increase, and the comparably large statistical bias (2%) would remain.</p>
<p>Now we will calculate the <strong>AKDEc</strong> based on the estimated parameters, and plot the home range of <code>animal2_gazelle</code>. Because of small <strong><em>effective sample size</em></strong>, we set optimal weights to <code>TRUE</code> for improved statistical efficiency:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>UD2_bpHREML <span class="ot">&lt;-</span> <span class="fu">akde</span>(animal2_gazelle, BOOT, <span class="at">weights =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(UD2_bpHREML)<span class="sc">$</span>CI</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we have calculated our home range for <code>animal2_gazelle</code>, with an estimated area of 13,274 square kilometers (with 95% confidence intervals: 3,231–30,280 km<sup>2</sup>). Our uncertainty with <code>animal2_gazelle</code> is substantially higher than with <code>animal1_buffalo</code>, as expected due to the small <strong><em>effective sample size</em></strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating an extent that includes both UDs at the 95% CI level:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>EXT <span class="ot">&lt;-</span> <span class="fu">extent</span>(<span class="fu">list</span>(UD2_pHREML, UD2_bpHREML), <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting pHREML and bootstrapped-pHREML side-by-side:</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal2_gazelle, <span class="at">UD =</span> UD2_pHREML, <span class="at">ext =</span> EXT)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="fu">expression</span>(<span class="st">"pHREML AKDE"</span>[<span class="st">"C"</span>]))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(animal2_gazelle, <span class="at">UD =</span> UD2_bpHREML, <span class="at">ext =</span> EXT)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="fu">expression</span>(<span class="st">"Bootstrapped pHREML wAKDE"</span>[<span class="st">"C"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AKDE_R-tutorial_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid"></p>
</div>
</div>
<p>The results presented here were generated with <code>R</code> version <code>4.2.3</code>, and <code>ctmm</code> version <code>1.1.1</code>.</p>
<hr>
</section>
</section>
</section>
<section id="glossary" class="level1">
<h1>Glossary</h1>
<p><a id="glossary"></a></p>
<p>– <em>Home range</em>: the area repeatedly used throughout an animal’s lifetime for all its normal behaviors and activities, excluding occasional exploratory moves.</p>
<p>– <em>Range residency</em>: the tendency of an animal to remain within their home range.</p>
<p>– <em>Home range crossing time</em>: the time required for an animal to cross the linear extent of its home range.</p>
<p>– <em>Absolute sample size</em> (<em>n</em>): the number of observations (fixes) in a dataset.</p>
<p>– <em>Effective sample size</em> (<em>N</em>): number of range crossings that occurred during the observation period. Can be roughly estimated by dividing the duration of the tracking dataset by the average <em>home range crossing time</em> parameter.</p>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography">
<div id="ref-calabrese_ctmm_2016" class="csl-entry" role="doc-biblioentry">
Calabrese, J. M., Fleming, C. H., &amp; Gurarie, E. (2016). Ctmm: <span>An</span> r package for analyzing animal relocation data as a continuous‐time stochastic process. <em>Methods in Ecology and Evolution</em>, <em>7</em>(9), 1124–1132.
</div>
<div id="ref-cross_disease_2009" class="csl-entry" role="doc-biblioentry">
Cross, P. C., Heisey, D. M., Bowers, J. A., Hay, C. T., Wolhuter, J., Buss, P., Hofmeyr, M., Michel, A. L., Bengis, R. G., &amp; Bird, T. L. F. (2009). Disease, predation and demography: Assessing the impacts of bovine tuberculosis on <span>African</span> buffalo by monitoring at individual and population levels. <em>Journal of Applied Ecology</em>, <em>46</em>(2), 467–475.
</div>
<div id="ref-fleming_fine-scale_2014" class="csl-entry" role="doc-biblioentry">
Fleming, C. H., Calabrese, J. M., Mueller, T., Olson, K. A., Leimgruber, P., &amp; Fagan, W. F. (2014). From fine-scale foraging to home ranges: A semivariance approach to identifying movement modes across spatiotemporal scales. <em>The American Naturalist</em>, <em>183</em>(5), E154–E167.
</div>
<div id="ref-fleming_overcoming_2019" class="csl-entry" role="doc-biblioentry">
Fleming, C. H., Noonan, M. J., Medici, E. P., &amp; Calabrese, J. M. (2019). Overcoming the challenge of small effective sample sizes in home‐range estimation. <em>Methods in Ecology and Evolution</em>, <em>10</em>(10), 1679–1689.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>